name: Run Puppeteer Script

on:
  push:
    branches:
      - main  # Trigger the workflow on main branch push
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Set Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer Script
        run: node puppeteer-script.js  # Replace with your script filename
